# Generated by Django 4.2.5 on 2023-11-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da disciplina', max_length=50, verbose_name='Nome')),
                ('codigo', models.CharField(help_text='Código da disciplina', max_length=20, unique=True, verbose_name='Codigo')),
                ('alunos', models.ManyToManyField(to='aluno.aluno')),
                ('curso', models.ForeignKey(help_text='Nome do curso', on_delete=django.db.models.deletion.CASCADE, to='curso.curso', verbose_name='Curso')),
            ],
        ),
    ]
