# Generated by Django 4.2.5 on 2023-11-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(help_text='Nome do professor', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='professor.professor', verbose_name='Professor'),
        ),
    ]
