# Generated by Django 4.2.5 on 2023-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_options'),
        ('disciplina', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(help_text='Alunos cadastrados', to='aluno.aluno', verbose_name='Alunos'),
        ),
    ]
