# Generated by Django 4.2.5 on 2023-11-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_servico_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
