# Generated by Django 4.2.5 on 2023-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Universidade', max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(help_text='Endereço da Universidade', max_length=120, verbose_name='Endereço')),
            ],
        ),
    ]
