# Generated by Django 4.2.5 on 2023-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do aluno', max_length=50, verbose_name='Nome')),
                ('matricula', models.DecimalField(decimal_places=0, help_text='Numero da matricula', max_digits=15, unique=True, verbose_name='Matricula')),
                ('cpf', models.DecimalField(decimal_places=0, help_text='Numero do CPF', max_digits=11, unique=True, verbose_name='Cpf')),
            ],
        ),
    ]
