# Generated by Django 4.2.5 on 2023-11-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
