# Generated by Django 4.2.5 on 2023-11-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do professor', max_length=50, verbose_name='Nome')),
                ('siape', models.DecimalField(decimal_places=0, help_text='Número do siape', max_digits=20, unique=True, verbose_name='Siape')),
                ('disciplina', models.ForeignKey(help_text='Nome da disciplina', on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='disciplina.disciplina', verbose_name='Disciplina')),
            ],
        ),
    ]
