# Generated by Django 4.2.5 on 2023-11-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
    ]
