# Generated by Django 4.2.5 on 2023-11-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_alter_funcionario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='foto',
        ),
    ]
