# Generated by Django 4.2.5 on 2023-11-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-horario'], 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
    ]
